Soccer_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('post/',include('post.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('list/', views.PostListView.as_view(),name='list'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('teamlist/', views.PostTeamListView.as_view(), name='teamlist'),
    path('teamdetail/<int:pk>', views.PostTeamDetailView.as_view(), name='teamdetail')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.UserSignUpView.as_view(),name='signup'),
    path('detail/', views.UserDetailView.as_view(),name='detail'),
    path('login/', views.UserLoginView.as_view(),name='login'),
    path('logout/', views.UserLogoutView.as_view(),name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Soccer_chat</title>

        <!-- Bootstrapを読み込む -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

        <!--  個別のCSS -->
        {% block customcss %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid justify-content-between">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'post:list' %}">Home</a>
            <a class="navbar-brand" href="{% url 'post:create' %}">投稿の新規作成</a>
            <a class="navbar-brand" href="{% url 'post:teamlist' %}">チーム一覧</a>
            <a class="navbar-brand" href="{% url 'user:logout' %}">ログアウト</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'user:home' %}">Home</a>
            <a class="navbar-brand ml-auto" href="{% url 'user:signup' %}">会員登録</a>
            <a class="navbar-brand ml-auto" href="{% url 'user:login' %}"> ログイン</a>
            {% endif %}
            </div>
        </nav>

        <!-- メインコンテンツ -->
        {% block content %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

  <section class="hero-section">
    <div class="hero-content">
      <h1>Welcome to Soccer News</h1>
      <p>ここではサーカー好きの人たちと意見を交換することができます。</p>
    </div>
  </section>  
{% endblock %}