Soccer_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('post/',include('post.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('list/', views.PostListView.as_view(),name='list'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('teamlist/', views.PostTeamListView.as_view(), name='teamlist'),
    path('teamdetail/<int:pk>', views.PostTeamDetailView.as_view(), name='teamdetail')
]

post/models.py
from django.db import models
from django.contrib.auth import get_user_model

from user import League


User = get_user_model()


class Common(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=("投稿者"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=('投稿日'))

    class Meta:
        abstract = True



class Team(models.Model):
    league = models.CharField(max_length=50, choices=League.LEAGUE_CHOICE, verbose_name=('リーグ'))
    logo = models.ImageField(upload_to='image/', verbose_name=('エンブレム'))
    location = models.CharField(max_length=150, verbose_name=('本拠地'))
    temaname = models.CharField(max_length=50, verbose_name=('チームネーム'))
    content = models.CharField(max_length=300, verbose_name=('チーム紹介'))

    def __str__(self):
        return self.temaname


class Post(Common):
    title = models.CharField(max_length=50, default='タイトルC', verbose_name=('タイトル'))
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, verbose_name=("チーム"))
    content = models.CharField(max_length=140, verbose_name=('投稿内容'))

    def __str__(self):
        return self.title

   
class Comment(Common):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="commented_post", verbose_name=("投稿"))
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=("投稿者"))
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name=('投稿日'))
    content = models.CharField(max_length=80, verbose_name=('投稿内容'))

    def __str__(self):
        return self.content

post/forms.py
from django import forms

from .models import Post, Team, Comment


class CreateForm(forms.ModelForm):
    title = forms.CharField(max_length=50)
    team = forms.ModelChoiceField(queryset=Team.objects.all(), required=False, widget=forms.Select())
    content = forms.CharField(max_length=140)
    class Meta:
        model = Post
        fields = ['content', 'team', 'title']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']

post/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, ListView, DetailView, DeleteView
import googlemaps

from .forms import CreateForm, CommentForm
from .models import Post, Team


class PostListView(LoginRequiredMixin, ListView):
    template_name = 'post/list.html'
    model = Post
    ordering = ['-created_at']
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team'] = Team.objects.all()
        return context


class PostCreateView(LoginRequiredMixin, FormView):
    template_name = 'post/create.html'
    form_class = CreateForm
    success_url = reverse_lazy('post:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['teams'] = Team.objects.all()
        return context
    
    def post(self, request, *args, **kwargs):
        create_form = CreateForm(request.POST)
        if create_form.is_valid():
            new_post = create_form.save(commit=False)
            title = create_form.cleaned_data['title']
            team = create_form.cleaned_data['team']
            content = create_form.cleaned_data['content']
            new_post.author = self.request.user
            new_post.save()
            return redirect('post:list')
        return redirect('post:list')


class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'post/detail.html'
    model = Post

    def get(self, request, pk):
        post_detail = Post.objects.get(id=pk)
        comment = post_detail.commented_post.all()
        comment_form = CommentForm()
        context = {
            'post': post_detail,
            'comment_form': comment_form,
            'comments': comment
        }
        return render(request, 'post/detail.html', context)

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        post_id = self.kwargs.get('pk')
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            post = Post.objects.get(id=post_id)
            comment.post = post
            comment.author = request.user
            comment.save()
            print('success')
            return redirect('post:detail', pk=post_id)
        return redirect('post:detail', pk=post_id)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'post/delete.html'
    model = Post
    success_url = reverse_lazy('post:list')


class PostTeamListView(LoginRequiredMixin, ListView):
    template_name = 'post/teamlist.html'
    model = Team
    ordering = ['league']


class PostTeamDetailView(LoginRequiredMixin, DetailView):
    template_name = 'post/teamdetail.html'
    model = Team

    def get(self, request, pk):
        team_detail = Team.objects.get(id=pk)
        all_post = Post.objects.filter(team_id=team_detail.id)
        gmaps = googlemaps.Client(key=settings.GOOGLE_MAPS_API_KEY)
        geocode_result = gmaps.geocode(team_detail.location)
        location = geocode_result[0]['geometry']['location']
        lat, lng = location['lat'], location['lng']
        context = {
            'team': team_detail,
            'posts': all_post,
            'lat': lat, 
            'lng': lng
        }
        return render(request, 'post/teamdetail.html', context)

templates/post/create.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/post/create.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
  <h1>新規作成</h1>
  <form method="post" class="create-form">
    {% csrf_token %}
    <div class="form-group">
      <input type="text" name="title" class="form-control form-title">
      <label class="form-label">タイトル</label>
    </div>

    <select name="team" class="form-select">
    {% for team in teams %}
        <option value="{{team.id}}">{{team}}</option>
    {% endfor %}
    </select>
    
    <div class="form-group">
      <textarea name="content" class="form-control form-content"></textarea>
      <label class="form-label">内容</label>
    </div>
    <button type="submit" class="btn-create">作成</button>
  </form>
{% endblock %}

templates/post/delete.html
{% extends 'base.html' %}
{% block content %}


<div class="message-body">
    タイトル: "{{ post.title }}"
    <br>
    投稿内容: "{{ post.content }}"
    <br>
    を削除しますか
</div>


<form method="POST">
    {% csrf_token %}
    <input class="button is-danger" type="submit" value="削除">
</form>

{% endblock content %}

templates/post/detail.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/post/detail.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="post-detail">
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <div class="post-meta">
      <p class="post-author">投稿者: {{ post.author.username }}</p>
      <p class="post-date">投稿時間: {{ post.created_at }}</p>
    </div>
    <hr>
    <h2>コメント</h2>
    {% for comment in comments %}
      <div class="comment">
        <p>{{ comment.content }}</p>
        <div class="comment-meta">
          <p class="comment-author">投稿者: {{ comment.author.username }}</p>
          <p class="comment-date">{{ comment.created_at }}</p>
        </div>
      </div>
      <hr>
    {% empty %}
      <p>コメントはまだありません</p>
    {% endfor %}
    <h3>コメントを追加する</h3>
    <form method="post">
      {% csrf_token %}
      {{ comment_form }}
      <button type="submit">追加</button>
    </form>
    {% if post.author.id == request.user.id %}
  <a style='right-top' href="{% url 'post:delete' post.id %}">削除ページへ</a>
  {% endif %}
  </div>
  
{% endblock %}

templates/post/list.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
  <link href='{% static 'css/post/list.css' %}' rel="stylesheet">
{% endblock %}

{% block content %}
  <h1><i class="fas fa-book-open"></i> 全ての投稿</h1>
  <ul class="post-list">
    {% for post in object_list %}
      <li class="post-list-item">
        <div class="team-logo">
          <img class="post-logo" src="{{ post.team.logo.url }}" alt="{{ post.team.temaname }}のロゴ">            
        </div>
        <div class="post-content">
          <div class="post-header">
            <h2><a href="{% url 'post:detail' post.pk %}">{{ post.title }}</a></h2>
          </div>
          <p>{{ post.content }}</p>
          <div class="post-meta">
            <p class="post-author"><i class="fas fa-user"></i> 投稿者: {{ post.author.username }}</p>
            <p class="post-date"><i class="fas fa-calendar-alt"></i> 投稿時間: {{ post.created_at }}</p>
          </div>
        </div>
      </li>
    {% empty %}
      <li><i class="fas fa-exclamation-triangle"></i> 投稿はまだありません</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/post/teamdetail.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/post/teamdetail.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="row team-detail">
    <div class="col-md-4">
      <img class="team-logo" src="{{ team.logo.url }}">
    </div>
    <div class="col-md-4">
      <h2>{{ team.temaname }}</h2>
      <p>リーグ: {{ team.league }}</p>
      <p>本拠地: {{ team.location }}</p>
      <p>{{ team.content }}</p>
    </div>
    <div class="col-md-4">
      <div id="map-container">
        <div id="map" style="height:250px; width:250px;"></div>
      </div>
    </div>
  </div>
  <hr>
  {% if posts %}
    <h3>関連する投稿</h3>
    <div class="row">
      {% for post in posts %}
        <div class="col-md-3">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'post:detail' post.pk %}">{{ post.title }}</a></h5>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
          </div><div class="row">
        {% endif %}
      {% endfor %}
    </div>
  {% else %}
    <p>まだ投稿がありません。</p>
  {% endif %}
  <script>
    function initMap() {
      var location = {lat: {{ lat }}, lng: {{ lng }}};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 16,
        center: location
      });
      var marker = new google.maps.Marker({
        position: location,
        map: map
      });
    }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&callback=initMap"></script>
{% endblock %}

templates/post/teamlist.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/post/teamlist.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container">
  <div class="row team-list">
    {% for team in object_list %}
    <div class="col-md-3 mb-4">
      <div class="card box-shadow">
        <img class="card-img-top" src="{{ team.logo.url }}" alt="{{ team.temaname }}">
        <div class="card-body">
          <h5 class="card-title text-center">
            <a href="{% url 'post:teamdetail' team.pk %}">{{ team.temaname }}</a>
          </h5>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row team-list">
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}