Soccer_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('post/',include('post.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('list/', views.PostListView.as_view(),name='list'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('teamlist/', views.PostTeamListView.as_view(), name='teamlist'),
    path('teamdetail/<int:pk>', views.PostTeamDetailView.as_view(), name='teamdetail')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.UserSignUpView.as_view(),name='signup'),
    path('detail/', views.UserDetailView.as_view(),name='detail'),
    path('login/', views.UserLoginView.as_view(),name='login'),
    path('logout/', views.UserLogoutView.as_view(),name='logout'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)

from .League import LEAGUE_CHOICE


class UserManager(BaseUserManager):
    
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('メールアドレスを必ず入力してください')
        elif not username:
            raise ValueError('名前を入力してください')
        user = self.model(
            username = username,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, email, password):
        user = self.create_user(
            username=username,
            email=email,
            password=password,
        )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50,verbose_name = 'ユーザー名')
    email = models.EmailField(max_length=255, unique=True,verbose_name = 'メールアドレス')
    favorite_league = models.CharField(max_length=50, choices=LEAGUE_CHOICE, default='Jリーグ', verbose_name = '好きなリーグ')
    content = models.CharField(max_length=500,verbose_name = '自己紹介')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username'] 
    
    objects = UserManager()
    
    class Meta:
        db_table = 'user'

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from . import models
from .League import LEAGUE_CHOICE


user = get_user_model()


class SignupForm(forms.ModelForm):
    email = forms.EmailField(label = 'メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user
    
    class Meta:
        model = models.User
        fields = ['password','email']

    
class DetailForm(forms.ModelForm):
    username = forms.CharField(max_length=50, label = 'ユーザー名')
    favorite_league = forms.ChoiceField(choices=LEAGUE_CHOICE, required=False,widget=forms.Select())
    content = forms.CharField(max_length=500,label = '自己紹介')

    class Meta:
        model = models.User
        fields = ['username','favorite_league','content']


class LoginForm(forms.Form):
    email = forms.EmailField(label = 'メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())

    class Meta:
        model = models.User
        fields = ['password','email']


class ChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password', 'is_staff', 'is_superuser', 'is_active')

    def clean_password(self):
        return self.initial['password']

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic.edit import FormView
from django.views.generic import View

from . import forms
from .League import LEAGUE_CHOICE


class UnauthenticatedOnly(UserPassesTestMixin):
    
    def test_func(self):
        return not self.request.user.is_authenticated
    
    def handle_no_permission(self):
        return redirect('post:list')

def home(request):
    return render(
        request, 'home.html'
    )

class UserSignUpView(FormView):
    template_name = 'user/signup.html'
    form_class = forms.SignupForm

    def post(self, request, *args, **kwargs):
        user_form = forms.SignupForm(request.POST)
        
        if user_form.is_valid():
            user_form.save()
            user = authenticate(email=user_form.cleaned_data['email'], password=user_form.cleaned_data['password'])
            login(request, user)
            return redirect('user:detail')
        else:
            
            return render(request, self.template_name, {'regist_form': self.form_class})


class UserDetailView(LoginRequiredMixin, FormView):
    template_name = 'user/detail.html'
    form_class = forms.DetailForm

    def get(self, request, *arugs, **kwargs):
        return render(request, self.template_name, {'leagues': LEAGUE_CHOICE})

    def post(self, request, *args,**kwargs):
        detail_form = forms.DetailForm(request.POST)
        if detail_form.is_valid():
            user = request.user
            user.username = detail_form.cleaned_data['username']
            user.favorite_league = detail_form.cleaned_data['favorite_league']
            user.content = detail_form.cleaned_data['content'],
            user.save()
            return redirect('post:list')
        else:
            print(detail_form)
            return render(request,self.template_name,{'regist_form':self.form_class})


class UserLoginView(UnauthenticatedOnly ,FormView):
    template_name = 'user/login.html'
    form_class = forms.LoginForm

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('post:list')
        return redirect('user:home')


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('user:home')

templates/user/detail.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/user/signup.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
<body class="text-center">
<main class="form-signin w-100 m-auto">
  <form method='POST'>
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">プロフィール設定</h1> 
    
    <div class="form-floating">
      <input id="username" type="text" name= "username" class="form-control">
      <label for="id_username">ユーザー名</label>
    </div>
    <div class="form-floating">
      
      <select name="favorite_league" class="form-control">
        {% for league in leagues %}
            <option value="{{league|first}}">{{league|first}}</option>
        {% endfor %}
      </select>
      <label for="floatingInput">好きなリーグ</label>
    </div>
    <div class="form-floating">
        <input id="content" type="text" name= "content" class="form-control">
        <label for="id_content">自己紹介</label>
      </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">登録</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; Soccer Chat</p>
  </form>
</main> 
</body>
{% endblock %}  

templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/user/signup.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
<body class="text-center">
<main class="form-signin w-100 m-auto">
  <form method='POST'>
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">ログイン</h1>
    
    <div class="form-floating">
      <input type="email" name= "email" class="form-control">
      <label for="floatingInput">メールアドレス</label>
    </div>
    <div class="form-floating">
      <input type="password" name = "password" class="form-control">
      <label for="floatingPassword">パスワード</label>
    </div>

    <button class="w-100 btn btn-lg btn-primary" type="submit">ログイン</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; Soccer Chat</p>
  </form>
</main>
</body>
{% endblock %}

templates/user/signup.html
{% extends 'base.html' %}
{% load static %}
{% block customcss %}
<link href='{% static 'css/user/signup.css' %}' rel="stylesheet">
{% endblock %}
{% block content %}
<body class="text-center">
<main class="form-signin w-100 m-auto">
  <form method='POST'>{% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">登録</h1>
    
    <div class="form-floating">
      <input type="email" name= "email" class="form-control">
      <label for="floatingInput">メールアドレス</label>
    </div>
    <div class="form-floating">
      <input type="password" name = "password" class="form-control">
      <label for="floatingPassword">パスワード</label>
    </div>

    <button class="w-100 btn btn-lg btn-primary" type="submit">登録</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; Soccer Chat</p>
  </form>
</main>
</body>
{% endblock %}